const LANGS={en:"English",hi:"हिन्दी",mr:"मराठी",gu:"ગુજરાતી",kn:"ಕನ್ನಡ",te:"తెలుగు",ta:"தமிழ்",ml:"മലയാളം"};
const T={
en:{tag:"The next generation field ecosystem for insurance advisors.",next:"Continue →",back:"Back",build:"We are building a connected advisor ecosystem.",build2:"An advisor does not need the same kind of help at every moment. Sometimes it is the opening, sometimes the question, sometimes the objection, sometimes the client’s real need, and sometimes the numbers.",sys:"Not five isolated apps. One connected field workflow.",usp:"Built for India. Designed in 8 languages.",usp2:"One ecosystem. One advisor experience. Eight languages.",feed:"Now we want to hear from you.",proto:"These are still prototypes.",feed2:"Before final pricing and launch, tell us which apps you would actually use, what feels affordable, and whether you prefer individual apps or one connected bundle.",which:"Which apps would you actually use?",choose:"Choose your interest level and an affordable monthly price.",def:"Definitely interested",maybe:"Maybe interested",no:"Not for me right now",bundle:"If all five came together as one bundle…",byes:"Yes, definitely",bmaybe:"Maybe, depending on price",bno:"I prefer individual apps",bprice:"Comfortable 5-app bundle price",review:"Review and submit",need:"What is the ONE thing you most want these apps to help you with?",name:"Your name",city:"City / Branch",submit:"Submit on WhatsApp",free:"Free learning communities",keep:"Keep learning with INZBIZ.",advisor:"For Insurance Advisors",joinA:"Join Advisors' Group",dos:"For Development Officers",joinD:"Join DOBE Group",ping:"Ping me for more info",again:"Start again",nr:"No response"},
hi:{tag:"बीमा सलाहकारों के लिए अगली पीढ़ी का फील्ड इकोसिस्टम।",next:"आगे बढ़ें →",back:"पीछे",build:"हम एक जुड़ा हुआ सलाहकार इकोसिस्टम बना रहे हैं।",build2:"हर समय सलाहकार को एक ही तरह की मदद नहीं चाहिए। कभी शुरुआत, कभी सही सवाल, कभी आपत्ति, कभी ग्राहक की वास्तविक जरूरत और कभी संख्याएँ चुनौती होती हैं।",sys:"पाँच अलग ऐप नहीं। एक जुड़ा हुआ फील्ड प्रवाह।",usp:"भारत के लिए बनाया गया। 8 भाषाओं में डिज़ाइन।",usp2:"एक इकोसिस्टम। एक सलाहकार अनुभव। आठ भाषाएँ।",feed:"अब हम आपकी राय चाहते हैं।",proto:"ये अभी प्रोटोटाइप हैं।",feed2:"अंतिम कीमत और लॉन्च से पहले बताइए कि आप कौन से ऐप वास्तव में उपयोग करेंगे, कौन सी कीमत किफायती है और अलग ऐप या पूरा बंडल क्या पसंद है।",which:"आप किन ऐप का वास्तव में उपयोग करेंगे?",choose:"हर ऐप के लिए रुचि और किफायती मासिक कीमत चुनें।",def:"पूरी रुचि है",maybe:"शायद रुचि है",no:"अभी मेरे लिए नहीं",bundle:"अगर पाँचों एक ही बंडल में मिलें…",byes:"हाँ, निश्चित रूप से",bmaybe:"शायद, कीमत पर निर्भर",bno:"मैं अलग-अलग ऐप पसंद करता/करती हूँ",bprice:"5-ऐप बंडल की सहज कीमत",review:"देखें और भेजें",need:"इन ऐप से आप सबसे अधिक किस एक मदद की उम्मीद करते हैं?",name:"आपका नाम",city:"शहर / शाखा",submit:"व्हाट्सऐप पर भेजें",free:"निःशुल्क अध्ययन समुदाय",keep:"INZBIZ के साथ सीखते रहें।",advisor:"बीमा सलाहकारों के लिए",joinA:"सलाहकार समूह से जुड़ें",dos:"विकास अधिकारियों के लिए",joinD:"DOBE समूह से जुड़ें",ping:"अधिक जानकारी के लिए संदेश करें",again:"फिर से शुरू करें",nr:"कोई प्रतिक्रिया नहीं"},
mr:{tag:"विमा सल्लागारांसाठी पुढील पिढीचे फील्ड इकोसिस्टम.",next:"पुढे →",back:"मागे",build:"आम्ही एक जोडलेले सल्लागार इकोसिस्टम तयार करत आहोत.",build2:"प्रत्येक वेळी सल्लागाराला एकच मदत लागत नाही. कधी सुरुवात, कधी प्रश्न, कधी हरकत, कधी ग्राहकाची खरी गरज आणि कधी आकडे हे आव्हान असते.",sys:"पाच स्वतंत्र अॅप्स नाहीत. एक जोडलेला फील्ड प्रवाह.",usp:"भारतासाठी तयार. 8 भाषांमध्ये डिझाइन.",usp2:"एक इकोसिस्टम. एक सल्लागार अनुभव. आठ भाषा.",feed:"आता तुमचा अभिप्राय हवा आहे.",proto:"हे अजून प्रोटोटाइप आहेत.",feed2:"अंतिम किंमत आणि लॉन्चपूर्वी कोणती अॅप्स प्रत्यक्ष वापराल, कोणती किंमत योग्य वाटते आणि स्वतंत्र अॅप की बंडल पसंत आहे ते सांगा.",which:"तुम्ही कोणती अॅप्स प्रत्यक्ष वापराल?",choose:"प्रत्येक अॅपसाठी रुची आणि योग्य मासिक किंमत निवडा.",def:"नक्कीच रस आहे",maybe:"कदाचित रस आहे",no:"आत्ता माझ्यासाठी नाही",bundle:"सर्व पाच एकाच बंडलमध्ये मिळाले तर…",byes:"हो, नक्की",bmaybe:"कदाचित, किंमतीवर",bno:"मला स्वतंत्र अॅप्स पसंत आहेत",bprice:"5-अॅप बंडलची योग्य किंमत",review:"पहा आणि पाठवा",need:"या अॅप्सनी तुम्हाला सर्वात जास्त कोणत्या एका गोष्टीत मदत करावी?",name:"तुमचे नाव",city:"शहर / शाखा",submit:"व्हॉट्सअॅपवर पाठवा",free:"मोफत अध्ययन समुदाय",keep:"INZBIZ सोबत शिकत रहा.",advisor:"विमा सल्लागारांसाठी",joinA:"सल्लागार समूहात सामील व्हा",dos:"विकास अधिकाऱ्यांसाठी",joinD:"DOBE समूहात सामील व्हा",ping:"अधिक माहितीसाठी संदेश",again:"पुन्हा सुरू करा",nr:"उत्तर नाही"},
gu:{tag:"વીમા સલાહકારો માટે આગામી પેઢીનું ફીલ્ડ ઇકોસિસ્ટમ.",next:"આગળ →",back:"પાછળ",build:"અમે જોડાયેલ સલાહકાર ઇકોસિસ્ટમ બનાવી રહ્યા છીએ.",build2:"દરેક સમયે સલાહકારને એક જ મદદ જોઈએ નહીં. ક્યારેક શરૂઆત, પ્રશ્ન, વાંધો, ગ્રાહકની સાચી જરૂરિયાત અથવા આંકડા મહત્વના બને છે.",sys:"પાંચ અલગ એપ્સ નહીં. એક જોડાયેલ ફીલ્ડ પ્રવાહ.",usp:"ભારત માટે બનાવેલું. 8 ભાષામાં ડિઝાઇન.",usp2:"એક ઇકોસિસ્ટમ. એક સલાહકાર અનુભવ. આઠ ભાષાઓ.",feed:"હવે તમારો પ્રતિસાદ જોઈએ છે.",proto:"આ હજુ પ્રોટોટાઇપ છે.",feed2:"અંતિમ કિંમત અને લોન્ચ પહેલાં કઈ એપ્સ ખરેખર વાપરશો, કઈ કિંમત યોગ્ય લાગે અને અલગ એપ કે બંડલ ગમે તે જણાવો.",which:"કઈ એપ્સ તમે ખરેખર વાપરશો?",choose:"દરેક એપ માટે રસ અને યોગ્ય માસિક કિંમત પસંદ કરો.",def:"ચોક્કસ રસ છે",maybe:"કદાચ રસ છે",no:"હમણાં મારા માટે નહીં",bundle:"બધી પાંચ એક બંડલમાં મળે તો…",byes:"હા, ચોક્કસ",bmaybe:"કદાચ, કિંમત પર",bno:"મને અલગ એપ્સ ગમે",bprice:"5-એપ બંડલ માટે યોગ્ય કિંમત",review:"જુઓ અને મોકલો",need:"આ એપ્સ તમને સૌથી વધુ એક કઈ બાબતમાં મદદ કરે તેવી ઈચ્છા છે?",name:"તમારું નામ",city:"શહેર / શાખા",submit:"વોટ્સએપ પર મોકલો",free:"મફત અભ્યાસ સમુદાયો",keep:"INZBIZ સાથે શીખતા રહો.",advisor:"વીમા સલાહકારો માટે",joinA:"સલાહકાર જૂથમાં જોડાઓ",dos:"ડેવલપમેન્ટ ઓફિસર્સ માટે",joinD:"DOBE જૂથમાં જોડાઓ",ping:"વધુ માહિતી માટે સંદેશ",again:"ફરી શરૂ કરો",nr:"પ્રતિસાદ નથી"},
kn:{tag:"ವಿಮೆ ಸಲಹೆಗಾರರಿಗಾಗಿ ಮುಂದಿನ ತಲೆಮಾರಿನ ಫೀಲ್ಡ್ ಇಕೋಸಿಸ್ಟಮ್.",next:"ಮುಂದೆ →",back:"ಹಿಂದೆ",build:"ನಾವು ಸಂಪರ್ಕಿತ ಸಲಹೆಗಾರರ ಇಕೋಸಿಸ್ಟಮ್ ನಿರ್ಮಿಸುತ್ತಿದ್ದೇವೆ.",build2:"ಪ್ರತಿ ಕ್ಷಣದಲ್ಲೂ ಒಂದೇ ಸಹಾಯ ಬೇಡ. ಕೆಲವೊಮ್ಮೆ ಆರಂಭ, ಪ್ರಶ್ನೆ, ಆಕ್ಷೇಪ, ಗ್ರಾಹಕರ ನಿಜವಾದ ಅಗತ್ಯ ಅಥವಾ ಅಂಕಿಗಳು ಮುಖ್ಯ.",sys:"ಐದು ಬೇರೆ ಆ್ಯಪ್‌ಗಳು ಅಲ್ಲ. ಒಂದು ಸಂಪರ್ಕಿತ ಫೀಲ್ಡ್ ಪ್ರವಾಹ.",usp:"ಭಾರತಕ್ಕಾಗಿ ನಿರ್ಮಿತ. 8 ಭಾಷೆಗಳಲ್ಲಿ ವಿನ್ಯಾಸ.",usp2:"ಒಂದು ಇಕೋಸಿಸ್ಟಮ್. ಒಂದು ಸಲಹೆಗಾರ ಅನುಭವ. ಎಂಟು ಭಾಷೆಗಳು.",feed:"ಈಗ ನಿಮ್ಮ ಅಭಿಪ್ರಾಯ ಬೇಕು.",proto:"ಇವು ಇನ್ನೂ ಪ್ರೋಟೋಟೈಪ್‌ಗಳು.",feed2:"ಅಂತಿಮ ಬೆಲೆ ಮತ್ತು ಬಿಡುಗಡೆಗೂ ಮೊದಲು ಯಾವ ಆ್ಯಪ್‌ಗಳನ್ನು ನಿಜವಾಗಿ ಬಳಸುತ್ತೀರಿ, ಯಾವ ಬೆಲೆ ಸೂಕ್ತ ಮತ್ತು ಪ್ರತ್ಯೇಕ ಆ್ಯಪ್ ಅಥವಾ ಬಂಡಲ್ ಯಾವುದು ಇಷ್ಟ ಎಂದು ತಿಳಿಸಿ.",which:"ಯಾವ ಆ್ಯಪ್‌ಗಳನ್ನು ನಿಜವಾಗಿ ಬಳಸುತ್ತೀರಿ?",choose:"ಪ್ರತಿ ಆ್ಯಪ್‌ಗೆ ಆಸಕ್ತಿ ಮತ್ತು ಸೂಕ್ತ ಮಾಸಿಕ ಬೆಲೆ ಆಯ್ಕೆಮಾಡಿ.",def:"ಖಂಡಿತ ಆಸಕ್ತಿ ಇದೆ",maybe:"ಬಹುಶಃ ಆಸಕ್ತಿ ಇದೆ",no:"ಈಗ ನನಗೆ ಬೇಡ",bundle:"ಎಲ್ಲ ಐದು ಒಂದೇ ಬಂಡಲ್‌ನಲ್ಲಿ ಬಂದರೆ…",byes:"ಹೌದು, ಖಂಡಿತ",bmaybe:"ಬಹುಶಃ, ಬೆಲೆಯ ಮೇಲೆ",bno:"ನನಗೆ ಪ್ರತ್ಯೇಕ ಆ್ಯಪ್‌ಗಳು ಇಷ್ಟ",bprice:"5-ಆ್ಯಪ್ ಬಂಡಲ್‌ಗೆ ಸೂಕ್ತ ಬೆಲೆ",review:"ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಕಳುಹಿಸಿ",need:"ಈ ಆ್ಯಪ್‌ಗಳು ನಿಮಗೆ ಹೆಚ್ಚು ಯಾವ ಒಂದು ವಿಷಯದಲ್ಲಿ ಸಹಾಯ ಮಾಡಬೇಕು?",name:"ನಿಮ್ಮ ಹೆಸರು",city:"ನಗರ / ಶಾಖೆ",submit:"ವಾಟ್ಸ್ಆಪ್‌ನಲ್ಲಿ ಕಳುಹಿಸಿ",free:"ಉಚಿತ ಅಧ್ಯಯನ ಸಮುದಾಯಗಳು",keep:"INZBIZ ಜೊತೆ ಕಲಿಯುತ್ತಿರಿ.",advisor:"ವಿಮೆ ಸಲಹೆಗಾರರಿಗಾಗಿ",joinA:"ಸಲಹೆಗಾರರ ಗುಂಪಿಗೆ ಸೇರಿ",dos:"ಅಭಿವೃದ್ಧಿ ಅಧಿಕಾರಿಗಳಿಗಾಗಿ",joinD:"DOBE ಗುಂಪಿಗೆ ಸೇರಿ",ping:"ಹೆಚ್ಚಿನ ಮಾಹಿತಿಗೆ ಸಂದೇಶ",again:"ಮತ್ತೆ ಆರಂಭಿಸಿ",nr:"ಪ್ರತಿಕ್ರಿಯೆ ಇಲ್ಲ"},
te:{tag:"బీమా సలహాదారుల కోసం తదుపరి తరం ఫీల్డ్ ఎకోసిస్టమ్.",next:"తర్వాత →",back:"వెనక్కి",build:"మేము అనుసంధానమైన సలహాదారుల ఎకోసిస్టమ్ నిర్మిస్తున్నాం.",build2:"ప్రతి సమయంలో ఒకే సహాయం అవసరం కాదు. ప్రారంభం, ప్రశ్న, అభ్యంతరం, నిజమైన అవసరం లేదా సంఖ్యలు వేర్వేరు సవాళ్లు.",sys:"ఐదు విడి యాప్‌లు కాదు. ఒక అనుసంధానమైన ఫీల్డ్ ప్రవాహం.",usp:"భారతదేశం కోసం. 8 భాషల్లో రూపకల్పన.",usp2:"ఒక ఎకోసిస్టమ్. ఒక సలహాదారు అనుభవం. ఎనిమిది భాషలు.",feed:"ఇప్పుడు మీ అభిప్రాయం కావాలి.",proto:"ఇవి ఇంకా ప్రోటోటైప్‌లు.",feed2:"చివరి ధర మరియు ప్రారంభానికి ముందు ఏ యాప్‌లు నిజంగా ఉపయోగిస్తారు, ఏ ధర సరైనది, విడి యాప్‌లు లేదా బండిల్ ఏది ఇష్టం చెప్పండి.",which:"ఏ యాప్‌లను నిజంగా ఉపయోగిస్తారు?",choose:"ప్రతి యాప్‌కు ఆసక్తి మరియు సరైన నెలవారీ ధర ఎంచుకోండి.",def:"ఖచ్చితంగా ఆసక్తి ఉంది",maybe:"బహుశా ఆసక్తి ఉంది",no:"ఇప్పుడు నాకు కాదు",bundle:"అన్ని ఐదు ఒకే బండిల్‌లో వస్తే…",byes:"అవును, ఖచ్చితంగా",bmaybe:"బహుశా, ధరపై",bno:"నాకు విడి యాప్‌లు ఇష్టం",bprice:"5-యాప్ బండిల్‌కు సరైన ధర",review:"చూసి పంపండి",need:"ఈ యాప్‌లు మీకు ఎక్కువగా ఏ ఒక్క విషయంలో సహాయం చేయాలి?",name:"మీ పేరు",city:"నగరం / శాఖ",submit:"వాట్సాప్‌లో పంపండి",free:"ఉచిత అధ్యయన సమూహాలు",keep:"INZBIZతో నేర్చుకుంటూ ఉండండి.",advisor:"బీమా సలహాదారుల కోసం",joinA:"సలహాదారుల గ్రూప్‌లో చేరండి",dos:"డెవలప్‌మెంట్ అధికారుల కోసం",joinD:"DOBE గ్రూప్‌లో చేరండి",ping:"మరింత సమాచారం కోసం సందేశం",again:"మళ్లీ ప్రారంభించండి",nr:"స్పందన లేదు"},
ta:{tag:"காப்பீட்டு ஆலோசகர்களுக்கான அடுத்த தலைமுறை களச் சூழல்.",next:"அடுத்து →",back:"பின்னால்",build:"இணைந்த ஆலோசகர் சூழலை உருவாக்குகிறோம்.",build2:"ஒவ்வொரு தருணத்திலும் ஒரே உதவி தேவையில்லை. தொடக்கம், கேள்வி, எதிர்ப்பு, உண்மையான தேவை, எண்கள் என சவால்கள் மாறுகின்றன.",sys:"ஐந்து தனி செயலிகள் அல்ல. ஒரு இணைந்த களப் பயணம்.",usp:"இந்தியாவுக்காக. 8 மொழிகளில் வடிவமைப்பு.",usp2:"ஒரு சூழல். ஒரு ஆலோசகர் அனுபவம். எட்டு மொழிகள்.",feed:"இப்போது உங்கள் கருத்து வேண்டும்.",proto:"இவை இன்னும் முன்மாதிரிகள்.",feed2:"இறுதி விலை மற்றும் வெளியீட்டுக்கு முன் எந்த செயலிகளை உண்மையில் பயன்படுத்துவீர்கள், எந்த விலை ஏற்றது, தனி செயலிகளா அல்லது தொகுப்பா என்று சொல்லுங்கள்.",which:"எந்த செயலிகளை உண்மையில் பயன்படுத்துவீர்கள்?",choose:"ஒவ்வொரு செயலிக்கும் ஆர்வத்தையும் ஏற்ற மாத விலையையும் தேர்வுசெய்க.",def:"நிச்சயம் ஆர்வம் உள்ளது",maybe:"ஒருவேளை ஆர்வம் உள்ளது",no:"இப்போது எனக்கு வேண்டாம்",bundle:"ஐந்தும் ஒரே தொகுப்பாக வந்தால்…",byes:"ஆம், நிச்சயம்",bmaybe:"ஒருவேளை, விலையைப் பொறுத்து",bno:"தனி செயலிகள் விருப்பம்",bprice:"5-செயலி தொகுப்புக்கு ஏற்ற விலை",review:"பார்த்து அனுப்புங்கள்",need:"இந்த செயலிகள் உங்களுக்கு அதிகம் உதவவேண்டிய ஒரே விஷயம் எது?",name:"உங்கள் பெயர்",city:"நகரம் / கிளை",submit:"வாட்ஸ்அப்பில் அனுப்புங்கள்",free:"இலவச கற்றல் குழுக்கள்",keep:"INZBIZ உடன் தொடர்ந்து கற்றுக்கொள்ளுங்கள்.",advisor:"காப்பீட்டு ஆலோசகர்களுக்கு",joinA:"ஆலோசகர் குழுவில் சேருங்கள்",dos:"வளர்ச்சி அதிகாரிகளுக்கு",joinD:"DOBE குழுவில் சேருங்கள்",ping:"மேலும் தகவலுக்கு செய்தி",again:"மீண்டும் தொடங்குங்கள்",nr:"பதில் இல்லை"},
ml:{tag:"ഇൻഷുറൻസ് അഡ്വൈസർമാർക്കായുള്ള അടുത്ത തലമുറ ഫീൽഡ് ഇക്കോസിസ്റ്റം.",next:"അടുത്തത് →",back:"പിന്നിലേക്ക്",build:"ബന്ധിപ്പിച്ച അഡ്വൈസർ ഇക്കോസിസ്റ്റമാണ് ഞങ്ങൾ നിർമ്മിക്കുന്നത്.",build2:"ഓരോ സമയത്തും ഒരേ സഹായമല്ല വേണ്ടത്. തുടക്കം, ചോദ്യം, എതിർപ്പ്, യഥാർത്ഥ ആവശ്യം, കണക്കുകൾ എന്നിങ്ങനെ വെല്ലുവിളികൾ മാറുന്നു.",sys:"അഞ്ച് വേർതിരിച്ച ആപ്പുകൾ അല്ല. ഒരു ബന്ധിപ്പിച്ച ഫീൽഡ് പ്രവാഹം.",usp:"ഇന്ത്യയ്ക്കായി നിർമ്മിച്ചു. 8 ഭാഷകളിൽ രൂപകൽപ്പന.",usp2:"ഒരു ഇക്കോസിസ്റ്റം. ഒരു അഡ്വൈസർ അനുഭവം. എട്ട് ഭാഷകൾ.",feed:"ഇപ്പോൾ നിങ്ങളുടെ അഭിപ്രായം വേണം.",proto:"ഇവ ഇപ്പോഴും പ്രോട്ടോട്ടൈപ്പുകളാണ്.",feed2:"അവസാന വിലയും ലോഞ്ചും മുമ്പ് ഏത് ആപ്പുകൾ യഥാർത്ഥത്തിൽ ഉപയോഗിക്കും, ഏത് വില അനുയോജ്യം, വേർതിരിച്ച ആപ്പോ ബണ്ടിലോ ഏത് ഇഷ്ടം എന്ന് പറയുക.",which:"ഏത് ആപ്പുകൾ യഥാർത്ഥത്തിൽ ഉപയോഗിക്കും?",choose:"ഓരോ ആപ്പിനും താൽപര്യവും അനുയോജ്യ മാസവിലയും തിരഞ്ഞെടുക്കുക.",def:"തീർച്ചയായും താൽപര്യമുണ്ട്",maybe:"ഒരുപക്ഷേ താൽപര്യമുണ്ട്",no:"ഇപ്പോൾ വേണ്ട",bundle:"എല്ലാ അഞ്ചും ഒരൊറ്റ ബണ്ടിലായി വന്നാൽ…",byes:"അതെ, തീർച്ചയായും",bmaybe:"ഒരുപക്ഷേ, വില അനുസരിച്ച്",bno:"വേർതിരിച്ച ആപ്പുകൾ ഇഷ്ടമാണ്",bprice:"5-ആപ്പ് ബണ്ടിലിന് അനുയോജ്യ വില",review:"പരിശോധിച്ച് അയയ്ക്കുക",need:"ഈ ആപ്പുകൾ നിങ്ങളെ ഏറ്റവും കൂടുതൽ ഏത് ഒരു കാര്യത്തിൽ സഹായിക്കണം?",name:"നിങ്ങളുടെ പേര്",city:"നഗരം / ശാഖ",submit:"വാട്സ്ആപ്പിൽ അയയ്ക്കുക",free:"സൗജന്യ പഠന സമൂഹങ്ങൾ",keep:"INZBIZ ഒപ്പം പഠനം തുടരുക.",advisor:"ഇൻഷുറൻസ് അഡ്വൈസർമാർക്കായി",joinA:"അഡ്വൈസർ ഗ്രൂപ്പിൽ ചേരുക",dos:"ഡെവലപ്‌മെന്റ് ഓഫീസർമാർക്കായി",joinD:"DOBE ഗ്രൂപ്പിൽ ചേരുക",ping:"കൂടുതൽ വിവരങ്ങൾക്ക് സന്ദേശം",again:"വീണ്ടും തുടങ്ങുക",nr:"പ്രതികരണം ഇല്ല"}
};
const apps=[
{v:"Start better.",d:"Human conversation guidance before insurance is mentioned.",q:"Don’t start with insurance. Start with the human being."},
{v:"Ask better.",d:"Questioning and discovery guidance for client conversations.",q:"Statements tell. Questions make clients think."},
{v:"Respond better.",d:"Live guidance for difficult objections and hesitation.",q:"Don’t fight the objection. Understand it."},
{v:"Navigate better.",d:"Client situation guidance from discovery to diagnosis and next action.",q:"Diagnose first. Recommend second."},
{v:"Explain the numbers better.",d:"Premium, benefit, protection, rider and year-wise plan intelligence.",q:"Calculate. Understand. Explain. Share."}
];
const names={
en:["Words That Open Doors","Questions Are the Answers","Objection Mastery","INZBIZ Insurance Compass","LIC Intelligence Engine"],
hi:["वर्ड्स दैट ओपन डोर्स","क्वेश्चंस आर द आन्सर्स","ऑब्जेक्शन मास्टरी","INZBIZ इंश्योरेंस कम्पास","एलआईसी इंटेलिजेंस इंजन"],
mr:["वर्ड्स दॅट ओपन डोअर्स","क्वेश्चन्स आर द आन्सर्स","ऑब्जेक्शन मास्टरी","INZBIZ इन्शुरन्स कंपास","एलआयसी इंटेलिजन्स इंजिन"],
gu:["વર્ડ્સ ધેટ ઓપન ડોર્સ","ક્વેશ્ચન્સ આર ધ આન્સર્સ","ઓબ્જેક્શન માસ્ટરી","INZBIZ ઇન્શ્યોરન્સ કમ્પાસ","એલઆઇસી ઇન્ટેલિજન્સ એન્જિન"],
kn:["ವರ್ಡ್ಸ್ ದಾಟ್ ಓಪನ್ ಡೋರ್ಸ್","ಕ್ವೆಶನ್ಸ್ ಆರ್ ದ ಆನ್ಸರ್ಸ್","ಆಬ್ಜೆಕ್ಷನ್ ಮಾಸ್ಟರಿ","INZBIZ ಇನ್ಶುರೆನ್ಸ್ ಕಂಪಾಸ್","ಎಲ್‌ಐಸಿ ಇಂಟೆಲಿಜೆನ್ಸ್ ಎಂಜಿನ್"],
te:["వర్డ్స్ దాట్ ఓపెన్ డోర్స్","క్వెషన్స్ ఆర్ ది ఆన్సర్స్","ఆబ్జెక్షన్ మాస్టరీ","INZBIZ ఇన్సూరెన్స్ కంపాస్","ఎల్‌ఐసి ఇంటెలిజెన్స్ ఇంజిన్"],
ta:["வேர்ட்ஸ் தாட் ஓபன் டோர்ஸ்","க்வெஷன்ஸ் ஆர் தி ஆன்சர்ஸ்","ஆப்ஜெக்ஷன் மாஸ்டரி","INZBIZ இன்ஷூரன்ஸ் கம்பஸ்","எல்‌ஐசி இன்டெலிஜென்ஸ் என்ஜின்"],
ml:["വേഡ്സ് ദാറ്റ് ഓപ്പൺ ഡോർസ്","ക്വഷൻസ് ആർ ദി ആൻസേഴ്സ്","ഓബ്ജക്ഷൻ മാസ്റ്ററി","INZBIZ ഇൻഷുറൻസ് കമ്പസ്","എൽ‌ഐസി ഇന്റലിജൻസ് എൻജിൻ"]
};
const flowWords={en:["OPEN","ASK","HANDLE","NAVIGATE","CALCULATE"],hi:["शुरुआत","पूछें","संभालें","दिशा","गणना"],mr:["सुरुवात","विचारा","हाताळा","दिशा","गणना"],gu:["શરૂઆત","પૂછો","સંભાળો","દિશા","ગણતરી"],kn:["ಆರಂಭ","ಕೇಳಿ","ನಿಭಾಯಿಸಿ","ದಿಕ್ಕು","ಗಣನೆ"],te:["ప్రారంభం","అడగండి","నిర్వహించండి","దిశ","లెక్కింపు"],ta:["தொடக்கம்","கேளுங்கள்","சமாளிக்கவும்","திசை","கணக்கு"],ml:["തുടക്കം","ചോദിക്കുക","കൈകാര്യം","ദിശ","കണക്കുകൂട്ടൽ"]};
let lang="en",page=1;
const state={interest:["","","","",""],prices:[300,300,300,300,300],bundle:"",bundlePrice:1199};
const tt=k=>T[lang][k]||T.en[k]||k;
const langSelect=()=>'<div class="lang"><select class="ls">'+Object.entries(LANGS).map(([c,n])=>'<option value="'+c+'" '+(c===lang?'selected':'')+'>'+n+'</option>').join('')+'</select></div>';
const top=n=>'<div class="top"><div class="mini">INZBIZ</div>'+langSelect()+'<span class="pageNo">'+n+'/14</span></div>';
const nav=(a,b)=>'<div class="bottom"><button class="btn ghost" data-go="'+a+'">'+tt("back")+'</button><button class="btn primary" data-go="'+b+'">'+tt("next")+'</button></div>';
function interestText(v){return v?tt(v):tt("nr")}
function render(){
 document.documentElement.lang=lang;document.getElementById("tag").textContent=tt("tag");document.getElementById("start").textContent=tt("next");
 let p='';
 p+='<section class="page" id="p2">'+top(2)+'<h1>'+tt("build")+'</h1><p class="lead">'+tt("build2")+'</p><div class="cards">'+[
 ["What should I say first?","Open naturally and become worth listening to."],["What should I ask next?","Discover what really matters before recommending."],["How should I handle this objection?","Understand first. Respond second."],["What does this client really need?","Diagnose before recommending."],["How do I explain premium and benefits?","Turn numbers into a clear client explanation."]
 ].map(x=>'<div class="card"><b>'+x[0]+'</b><span>'+x[1]+'</span></div>').join('')+'</div>'+nav(1,3)+'</section>';
 p+='<section class="page" id="p3">'+top(3)+'<h1>'+tt("sys")+'</h1><div class="flow">'+names[lang].map((n,i)=>'<div class="flowRow"><strong>'+flowWords[lang][i]+'</strong><div><b>'+n+'</b><small>'+apps[i].v+'</small></div></div>').join('')+'</div>'+nav(2,4)+'</section>';
 for(let i=0;i<5;i++){const n=4+i;p+='<section class="page" id="p'+n+'">'+top(n)+'<div class="kicker">'+apps[i].v+'</div><h1>'+names[lang][i]+'</h1><p class="lead">'+apps[i].d+'</p><div class="quote">'+apps[i].q+'</div><div class="card"><div class="points"><div class="point">✓ Practical field guidance</div><div class="point">✓ Built for real client conversations</div><div class="point">✓ Learn and practise before meetings</div><div class="point">✓ Designed for mobile use</div><div class="point">✓ Part of one connected advisor ecosystem</div></div></div>'+nav(n-1,n+1)+'</section>'}
 p+='<section class="page" id="p9">'+top(9)+'<h1>'+tt("usp")+'</h1><div class="usp"><b>'+tt("usp2")+'</b><div class="chips">'+Object.values(LANGS).map(n=>'<span class="chip">'+n+'</span>').join('')+'</div></div>'+nav(8,10)+'</section>';
 p+='<section class="page" id="p10">'+top(10)+'<h1>'+tt("feed")+'</h1><div class="feedbackIntro"><b>'+tt("proto")+'</b><p>'+tt("feed2")+'</p></div><div class="card" style="margin-top:12px"><b>No purchase now</b><span>This is feedback only. Nothing is being charged or booked.</span></div>'+nav(9,11)+'</section>';
 p+='<section class="page" id="p11">'+top(11)+'<h1>'+tt("which")+'</h1><p class="lead">'+tt("choose")+'</p><div class="feedback">'+names[lang].map((n,i)=>'<div class="feedbackCard"><h3>'+n+'</h3><div class="choiceGrid">'+["def","maybe","no"].map(v=>'<button class="choice '+(state.interest[i]===v?'active':'')+'" data-i="'+i+'" data-v="'+v+'">'+tt(v)+'</button>').join('')+'</div><div class="prices">'+[200,300,400,500].map(v=>'<button class="price '+(state.prices[i]===v?'active':'')+'" data-pi="'+i+'" data-p="'+v+'">₹'+v+'</button>').join('')+'</div></div>').join('')+'</div>'+nav(10,12)+'</section>';
 p+='<section class="page" id="p12">'+top(12)+'<h1>'+tt("bundle")+'</h1><div class="choiceGrid"><button class="choice '+(state.bundle==="yes"?'active':'')+'" data-b="yes">'+tt("byes")+'</button><button class="choice '+(state.bundle==="maybe"?'active':'')+'" data-b="maybe">'+tt("bmaybe")+'</button><button class="choice '+(state.bundle==="no"?'active':'')+'" data-b="no">'+tt("bno")+'</button></div><div class="rangeCard"><div class="rangeHead"><b>'+tt("bprice")+'</b><strong id="bv">₹'+state.bundlePrice+'</strong></div><input id="br" type="range" min="999" max="1500" step="50" value="'+state.bundlePrice+'"><div class="note">₹999 to ₹1,500</div></div>'+nav(11,13)+'</section>';
 p+='<section class="page" id="p13">'+top(13)+'<h1>'+tt("review")+'</h1><div class="summary">'+names[lang].map((n,i)=>'<div class="card"><b>'+n+'</b><span>'+interestText(state.interest[i])+(state.interest[i]&&state.interest[i]!=="no"?' • ₹'+state.prices[i]:'')+'</span></div>').join('')+'<div class="card"><b>5-App Bundle</b><span>'+(state.bundle==="yes"?tt("byes"):state.bundle==="maybe"?tt("bmaybe"):state.bundle==="no"?tt("bno"):tt("nr"))+' • ₹'+state.bundlePrice+'</span></div></div><div class="field"><label>'+tt("need")+'</label><textarea id="need"></textarea></div><div class="field"><label>'+tt("name")+'</label><input id="name"></div><div class="field"><label>'+tt("city")+'</label><input id="city"></div><div class="bottom"><button class="btn ghost" data-go="12">'+tt("back")+'</button><a class="btn secondary" id="send" href="#" target="_blank" rel="noopener">'+tt("submit")+'</a></div></section>';
 p+='<section class="page" id="p14">'+top(14)+'<h1>'+tt("free")+'</h1><p class="lead">'+tt("keep")+'</p><div class="community"><div class="communityCard"><div class="badge">FG</div><h3>'+tt("advisor")+'</h3><p>Financial Guardian. Free practical micro-lessons in 8 languages.</p><a class="btn secondary" href="https://chat.whatsapp.com/B8qzrfXDCA3AzzWmwlVlVX" target="_blank" rel="noopener">'+tt("joinA")+'</a></div><div class="communityCard"><div class="badge">DOBE</div><h3>'+tt("dos")+'</h3><p>Free Development Officer micro-lessons in 8 languages.</p><a class="btn primary" href="https://chat.whatsapp.com/IghtmaFOsdAB2TJY5PnrXs" target="_blank" rel="noopener">'+tt("joinD")+'</a></div><div class="communityCard"><h3>Nagaraj B. S.</h3><p>Founder, INZBIZ Foundation<br>9845034603</p><a class="btn ghost" href="https://wa.me/919845034603" target="_blank" rel="noopener">'+tt("ping")+'</a></div></div><div class="bottom"><button class="btn ghost" data-go="13">'+tt("back")+'</button><button class="btn primary" id="again">'+tt("again")+'</button></div></section>';
 document.getElementById("pages").innerHTML=p;bind();
}
function show(n){page=n;document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById("p"+n).classList.add("active");window.scrollTo(0,0)}
function message(){let a=["INZBIZ Advisor Apps Feedback",""];state.interest.forEach((v,i)=>a.push(names[lang][i]+": "+interestText(v)+(v&&v!=="no"?" | ₹"+state.prices[i]:"")));a.push("","5-App Bundle: "+(state.bundle==="yes"?tt("byes"):state.bundle==="maybe"?tt("bmaybe"):state.bundle==="no"?tt("bno"):tt("nr")),tt("bprice")+": ₹"+state.bundlePrice);const need=document.getElementById("need")?.value.trim(),name=document.getElementById("name")?.value.trim(),city=document.getElementById("city")?.value.trim();if(need)a.push("",tt("need")+": "+need);if(name)a.push(tt("name")+": "+name);if(city)a.push(tt("city")+": "+city);return a.join("\n")}
function bind(){
 document.querySelectorAll(".ls").forEach(s=>s.onchange=e=>{lang=e.target.value;render();show(page)});
 document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>show(+b.dataset.go));
 document.querySelectorAll("[data-i]").forEach(b=>b.onclick=()=>{state.interest[+b.dataset.i]=b.dataset.v;render();show(11)});
 document.querySelectorAll("[data-pi]").forEach(b=>b.onclick=()=>{state.prices[+b.dataset.pi]=+b.dataset.p;render();show(11)});
 document.querySelectorAll("[data-b]").forEach(b=>b.onclick=()=>{state.bundle=b.dataset.b;render();show(12)});
 const br=document.getElementById("br");if(br)br.oninput=e=>{state.bundlePrice=+e.target.value;document.getElementById("bv").textContent="₹"+state.bundlePrice};
 const send=document.getElementById("send");if(send)send.onclick=()=>{send.href="https://wa.me/919845034603?text="+encodeURIComponent(message());setTimeout(()=>show(14),100)};
 const again=document.getElementById("again");if(again)again.onclick=()=>location.reload();
}
document.getElementById("start").onclick=()=>show(2);render();